---
- name: Provision VM
  hosts: all
  become: yes
  become_method: sudo
  remote_user: pxeboot
  tasks:
    #- import_tasks: chapter2/pam_pwquality.yml
    - import_tasks: pxeboot/user_and_group.yml
    - import_tasks: pxeboot/authorized_keys.yml
    - import_tasks: pxeboot/interfaces.yml
    - import_tasks: pxeboot/install_dnsmasq.yml
  handlers:
    - import_tasks: handlers/restart_ssh.yml
    - import_tasks: handlers/restart_networking.yml
